import {Area, Gender, Member} from '@prisma/client'

export type CreateMemberDTO = {
  birthYear: number
  familyId: string
  fullName: string
  gender: Gender
  // id: string -- usually generated by backend? But if DTO is input, maybe not needed.
  isRepresentative?: boolean
}

export interface MemberWithFamily extends Member {
  age?: number
  family: {
    area?: Area
    areaId: string
    groupId: string
    id: string
    name: string
  }
  sao?: string
}
