import './globals.css'

import type {Metadata} from 'next'
import {Geist, Geist_Mono} from 'next/font/google'

import {MainNav} from '@/components/main-nav'
import {ThemeProvider} from '@/components/theme-provider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Cúng Sao',
  description: 'Generated by Antigravity - Vinh Pham',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
        suppressHydrationWarning
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <MainNav />
          <main className="flex-1 container mx-auto pt-24 pb-12 px-4">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  )
}
